# Generated by Django 4.1.3 on 2022-12-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grapcard',
            old_name='Freq',
            new_name='GrFreq',
        ),
        migrations.RenameField(
            model_name='procrssor',
            old_name='ClFreq',
            new_name='ProcFreq',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='ClFreq',
            new_name='RamFreq',
        ),
    ]
