# Generated by Django 4.1.3 on 2022-12-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_rename_freq_grapcard_grfreq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grapcard',
            name='GrName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procrssor',
            name='ProcName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='RAMName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
