# Generated by Django 4.1.3 on 2022-12-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0004_rename_procrssor_processor'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('EmailConf', models.BooleanField()),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('PhoneConf', models.BooleanField()),
                ('AccCreation', models.DateTimeField()),
                ('LastOnline', models.DateTimeField()),
                ('Role', models.CharField(choices=[('A', 'Admin'), ('U', 'User')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastInput', models.CharField(max_length=256)),
                ('LastOptions', models.CharField(max_length=256)),
                ('Date', models.DateTimeField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.user')),
            ],
        ),
    ]
