# Generated by Django 4.1.3 on 2023-03-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0005_user_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='AccCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='LastOnline',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
