# Generated by Django 4.1.3 on 2023-03-26 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comp', '0006_alter_history_date_alter_user_acccreation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=10)),
                ('memory_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.memorytype')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='grapcard',
            options={'ordering': ['id'], 'verbose_name': 'Graphical Crad', 'verbose_name_plural': 'Graphical Cards'},
        ),
        migrations.AlterModelOptions(
            name='processor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='grapcard',
            old_name='GrFreq',
            new_name='effective_mem_freq',
        ),
        migrations.RenameField(
            model_name='grapcard',
            old_name='GrName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='grapcard',
            old_name='VidMem',
            new_name='proc_frequency',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='LastInput',
            new_name='last_input',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='LastOptions',
            new_name='last_results',
        ),
        migrations.RenameField(
            model_name='processor',
            old_name='ProcFreq',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='processor',
            old_name='ProcName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='RamFreq',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='RAMName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='User_id',
        ),
        migrations.AddField(
            model_name='grapcard',
            name='video_memory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='motherboard',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.socket'),
        ),
        migrations.AddField(
            model_name='history',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processor',
            name='socket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comp.socket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='memory_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comp.memorytype'),
            preserve_default=False,
        ),
    ]
