# Generated by Django 4.1.3 on 2023-03-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0007_memorytype_motherboard_socket_alter_grapcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grapcard',
            name='recomend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='recomend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processor',
            name='recomend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ram',
            name='recomend',
            field=models.IntegerField(default=0),
        ),
    ]
