# Generated by Django 4.1.3 on 2023-03-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0008_grapcard_recomend_motherboard_recomend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='max_memory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grapcard',
            name='recomend',
            field=models.IntegerField(default=0, verbose_name='Popularity'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='recomend',
            field=models.IntegerField(default=0, verbose_name='Popularity'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='recomend',
            field=models.IntegerField(default=0, verbose_name='Popularity'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='recomend',
            field=models.IntegerField(default=0, verbose_name='Popularity'),
        ),
    ]
