# Generated by Django 4.1.3 on 2023-04-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0009_motherboard_max_memory_alter_grapcard_recomend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='last_input',
        ),
        migrations.RemoveField(
            model_name='history',
            name='last_results',
        ),
        migrations.AddField(
            model_name='history',
            name='grap_card_res',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='motherboard_res',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='processor_res',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='ram_re',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
