# Generated by Django 4.1.3 on 2023-04-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0010_remove_history_last_input_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='ram_re',
            new_name='ram_res',
        ),
    ]
