# Generated by Django 4.1.3 on 2023-05-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0013_history_comp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grapcard',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='processor',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ram',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
