# Generated by Django 4.1.3 on 2023-05-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0014_alter_grapcard_name_alter_motherboard_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='frequency',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ram',
            name='frequency',
            field=models.FloatField(),
        ),
    ]
